### ISSUE TITLE
No longer seeing "PostCSS" as a syntax option

### ISSUE THREAD

**Issue by elliottmangham** [widersky/postcss-nova-plugin#3] opened 2022-11-28 17:00 UTC
Hey,

Since the latest update (1.0.0), I can no longer see "PostCSS" listed as a syntax. I've tried restarting Nova, reinstalling "PostCSS Syntax" but I do see it listed:
![Shared Upload (2022-11-28 at 4 58 42)](https://user-images.githubusercontent.com/12933804/204337058-728feb5e-ab3d-4067-bf46-d04402a9ec95.png)

Thank you!

**Comment by widersky** [comment] 2022-11-29 07:07
Interesting, I'll look at it! Thank you for the report!

**Comment by mattias78** [comment] 2022-12-02 02:01
Same issue for me, updated Nova to latest (Build 472415), uninstalled / reinstalled the plugin, can't see the syntax as an option.

**Comment by djch** [comment] 2022-12-05 23:33
Same problem here

**Comment by widersky** [comment] 2022-12-06 06:37
@mattias78 @djch The problem actually occurs, but only on the downloaded version. When I activate the plugin in the developer version, everything works without any issues. It's hard for me to say what the problem is, I hope to solve it soon 👌🏻

**Comment by djch** [comment] 2022-12-07 22:57
Thanks for your time @widersky. I'm surprised I managed to put up with incorrectly highlighted PostCSS in Nova for so long before your extension came along. Hopefully not too challenging to figure out.

**Comment by widersky** [comment] 2022-12-09 18:09
Fixed in 1.1.0. Should be available to download soon :)

**Closed as completed by widersky** 2022-12-09 18:09 UTC
Labels: bug
